# Generated by Django 5.1.1 on 2025-07-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bhk', models.CharField(choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('4bhk+', '4BHK+')], max_length=10)),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=12)),
                ('listed_by', models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent'), ('builder', 'Builder')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=14)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold', 'SOld'), ('rented', 'Rented')], max_length=20)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
