# Generated by Django 5.1.1 on 2025-07-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='require',
            field=models.CharField(choices=[('ready', 'Ready to Move'), ('under_construction', 'Under Construction'), ('launching_soon', 'Launching Soon'), ('possession_later', 'Possession Later')], default='ready', max_length=30),
        ),
    ]
