# Generated by Django 5.1.1 on 2025-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_updated_on_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='business_type',
            field=models.CharField(blank=True, help_text='e.g. Office, Shop, Warehouse', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, help_text='e.g. North, East, West', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.FloatField(blank=True, help_text='Area in square yards/acres', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.CharField(blank=True, choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('4bhk+', '4BHK+')], max_length=10, null=True),
        ),
    ]
