# Generated by Django 5.1.1 on 2025-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='buyer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('dealer', 'Dealer')], default='Individual', max_length=20),
        ),
    ]
