# Generated by Django 5.1.1 on 2025-09-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_localityreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
    ]
