# Generated by Django 5.1.1 on 2025-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_city_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.CharField(choices=[('new', 'New Construction'), ('0-1', 'Less than 1 Year'), ('1-5', '1-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], help_text='e.g. North, East, West', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='properties.feature'),
        ),
    ]
