# Generated by Django 5.1.1 on 2025-09-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_feature_property_floor_number_property_furnishing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10),
        ),
    ]
