# Generated by Django 5.1.1 on 2025-09-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_property_deal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='parking_spaces',
        ),
    ]
