# Generated by Django 5.1.1 on 2025-09-17 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_property_parking_spaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localityreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='localityreview',
            name='property',
        ),
        migrations.RemoveField(
            model_name='localityreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='localityreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localityreview',
            name='cleanliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localityreview',
            name='connectivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localityreview',
            name='power_supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localityreview',
            name='public_transport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localityreview',
            name='related_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locality_reviews', to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localityreview',
            name='safety',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localityreview',
            name='water_supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='localityreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localityreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
