# Generated by Django 5.1.1 on 2025-09-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_alter_localityreview_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalityReview',
        ),
    ]
