# Generated by Django 5.1.1 on 2025-09-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_delete_localityreview'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS properties_localityreview;")
    ]

