# Generated by Django 5.1.1 on 2025-09-17 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20250918_0031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='properties.city')),
            ],
            options={
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LocalityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.IntegerField(default=0)),
                ('safety', models.IntegerField(default=0)),
                ('public_transport', models.IntegerField(default=0)),
                ('water_supply', models.IntegerField(default=0)),
                ('power_supply', models.IntegerField(default=0)),
                ('cleanliness', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.locality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
