# Generated by Django 5.1.1 on 2025-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_remove_property_city_remove_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localityfeedback',
            name='years_lived',
            field=models.IntegerField(default=0),
        ),
    ]
