# Generated by Django 5.1.1 on 2025-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_localityfeedback_years_lived'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
