# Generated by Django 5.1.1 on 2025-09-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_property_is_active_userprofile_delete_requested_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='delete_requested_at',
        ),
    ]
