# Generated by Django 5.1.1 on 2025-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_remove_userprofile_delete_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scheduled_deletion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
