# Generated by Django 5.1.1 on 2025-09-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_recent_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recent_viewed',
            old_name='viewwd_at',
            new_name='viewed_at',
        ),
    ]
