# Generated by Django 5.1.1 on 2025-09-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_rename_viewwd_at_recent_viewed_viewed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recent_viewed',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterField(
            model_name='recent_viewed',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='properties.property'),
        ),
    ]
