# Generated by Django 5.1.1 on 2025-09-24 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_alter_recent_viewed_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recent_viewed',
            new_name='Recentviewed',
        ),
    ]
