# Generated by Django 5.1.1 on 2025-09-25 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_rename_recent_viewed_recentviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentviewed',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='recentviewed',
            unique_together={('user', 'property')},
        ),
    ]
