# Generated by Django 5.1.1 on 2025-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_alter_recentviewed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localityfeedback',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
