# Generated by Django 5.1.1 on 2025-09-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_localityfeedback_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentviewed',
            options={'ordering': ['-viewed_at']},
        ),
    ]
