# Generated by Django 5.1.1 on 2025-09-25 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_alter_recentviewed_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentviewed',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='recentviewed',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_user_property'),
        ),
    ]
