# Generated by Django 5.1.1 on 2025-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_alter_recentviewed_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=20),
        ),
    ]
