# Generated by Django 5.1.1 on 2025-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
