# Generated by Django 5.1.1 on 2025-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_property_apartment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
