# Generated by Django 5.1.1 on 2025-09-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_property_rent_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='require',
            field=models.CharField(choices=[('ready to move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('launching_soon', 'Launching Soon')], default='ready to move', max_length=30),
        ),
    ]
