# Generated by Django 5.1.1 on 2025-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_alter_property_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='require',
            field=models.CharField(choices=[('ready', 'Ready to Move'), ('under_construction', 'Under Construction'), ('launching_soon', 'Launching Soon')], default='ready to move', max_length=30),
        ),
    ]
