# Generated by Django 5.1.1 on 2025-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_userprofile_email_verified_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='localityfeedback',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
