# Generated by Django 5.1.1 on 2025-10-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0052_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_unit',
            field=models.CharField(default='sq.ft', help_text='sq.ft, sq.yd, acre', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='boundary_wall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration',
            field=models.CharField(blank=True, help_text='e.g. 11 months / 3 years', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('poa', 'Power of Attorney'), ('govt', 'Government Land')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_width',
            field=models.IntegerField(blank=True, help_text='Width in feet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural')], max_length=50, null=True),
        ),
    ]
