# Generated by Django 5.1.1 on 2025-10-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_property_area_unit_property_boundary_wall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='business_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('shop', 'Shop'), ('restaurant', 'Restaurant'), ('warehouse', 'Warehouse'), ('factory', 'Factory')], help_text='e.g. Office, Shop, Warehouse', max_length=100, null=True),
        ),
    ]
