# Generated by Django 5.1.1 on 2025-10-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0054_property_seats_alter_property_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_posts_remaining',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
