# Generated by Django 5.1.1 on 2025-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0055_userprofile_free_posts_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='apartment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
